# Generated by Django 5.1.4 on 2025-02-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('stock', models.IntegerField(blank=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('id_tipo_productos', models.IntegerField(blank=True)),
                ('estado', models.BooleanField(blank=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
