# Generated by Django 5.1.4 on 2025-02-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True)),
                ('fecha', models.DateTimeField(blank=True)),
                ('id_producto', models.IntegerField(blank=True)),
                ('estado', models.BooleanField(blank=True)),
            ],
            options={
                'db_table': 'inventarios',
            },
        ),
    ]
