# Generated by Django 5.1.4 on 2025-02-20 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarios',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
