# Generated by Django 5.1.4 on 2025-02-20 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cortesias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_personal', models.IntegerField(blank=True)),
                ('id_producto', models.IntegerField(blank=True)),
                ('cantidad', models.IntegerField(blank=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'db_table': 'cortesias',
            },
        ),
        migrations.AddField(
            model_name='detallesventas',
            name='estado',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='detallesventas',
            name='id_venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='ventas.ventas'),
        ),
    ]
